# -*- coding: utf-8 -*-
"""EX3_RGBComposites.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wZ1_todGyNeercmraBVLzPiK6xVf7xS4

# Remote Sensing Data & Methods


<br>
<font size="6"> <b> Landsat 9 <b> </font>

<font size="4"> <b> L2 Product and RGB Composits<font color='rgba(200,0,0,0.2)'> </font> </b> </font>

<font size="4"> <b> Dr. M. Adnan Siddique, and Ehtasham Naseer</b>
<font size="3">  <br>
<font> <b> May 12, 2026 </b></font>
</font>

### Reflectance

Reflectance is the ratio of the reflected radiation from a surface to the incoming radiation (irradiance) incident upon that surface.
It is a unitless quantity, typically expressed as a percentage or a value between 0 and 1.

Note: Reflectance is a surface property and is crucial for identifying materials, as different materials reflect light differently at various wavelengths. In many ways, we prefer to work with **reflectance** rather than spectral **radiance**, given its direct dependence on the material properies, and in an ideal sense, its independence from the illumination conditions (under uniform conditions). In that sense, it is purely a function of the material's properties and surface geometry.

## Preliminaries

### Activate Conda environment

If you set up the conda environment named `rsdm` previously, please activate it now:

```bash
conda activate rsdm
```

# Part I

### Setting up local directory
"""

import os

# change directory to desired local directory on your machine
rootDirectory = "/Users/ehtashamnaseer/Desktop/RSDM-2026/excercises/"
os.chdir(rootDirectory)

# relative path to data folder
dataDirectory = os.path.join(rootDirectory, "dataset/Landsat9/LC09_L2SP_150038_20240803_20240804_02_T1/")

"""### Convert 16-bit DNs to Reflectance

The scaling factors are available in the metadata file: `LC09_L2SP_150038_20240803_20240804_02_T1_MTL.txt`.
"""

Landsat9_mtt_dict = {}

# Reading in the metadata
metadata_filename = os.path.join(dataDirectory, "LC09_L2SP_150038_20240803_20240804_02_T1_MTL.txt")
with open(metadata_filename, 'r') as _:
    for line in _:
        line = line.strip()
        if line != 'END':
            key, value = line.split('=')
            key = key.rstrip()
            Landsat9_mtt_dict[key] = value

key = None
value = None

"""Accessing scaling factors from the metadata"""

band = 4

# multiplicative rescaling factor for band 4
print(Landsat9_mtt_dict[f"REFLECTANCE_MULT_BAND_{band}"])

# additive rescaling factor for band 4
print(Landsat9_mtt_dict[f"REFLECTANCE_ADD_BAND_{band}"])

"""Reading in the image:"""

# Band # 4 (Red) of the Landsat scene, acquired on August 3, 2024
band = 4 # for dynamically setting the band
band_filename = os.path.join(dataDirectory, f"LC09_L2SP_150038_20240803_20240804_02_T1_SR_B{band}.TIF")

import rioxarray
dn_image = rioxarray.open_rasterio(band_filename)
dn_image.head()

dn_image.rio.crs

"""Read the conversion factors:"""

import numpy as np

m_lambda =
a_lambda =

"""Checking no data value:"""

# Access the no data value
no_data_value = dn_image.rio.nodata
print(f"Current no data value: {no_data_value}")

"""Calculation for conversion of DNs to reflectance:"""

reflectance_band =
dn_image = None

"""Plotting the band:"""

no_data_mask = (reflectance_band == no_data_value)
reflectance_band.sel(band = 1).where(~no_data_mask).plot(cmap = 'gray')

# Define the slice boundaries for zooming in (row and column indices)
col_start, col_end = 275000, 325000  # Adjust these values based on the area of interest
row_start, row_end = int(3532161.399690), int(3501924.303435)

# Slice the array to zoom in
zoomed_in_area = reflectance_band.sel(y=slice(row_start, row_end), x=slice(col_start, col_end))
zoomed_in_area.plot(figsize = (6,6),cmap = 'gray')

zoomed_in_area = None

"""Write down a function that reads in the a band, applies the scaling and additive factors and then returns a sliced version."""

#---> Your code here <---
def get_sliced_band_from_L2(data_directory, band_num, landsat9_mtt_dict):



    return

band4 = get_sliced_band_from_L2(dataDirectory, 4, Landsat9_mtt_dict)
band4.plot(figsize = (6,6),cmap = 'gray');

"""### Composites

#### Natural Color Image
> band combination: 4,3,2
"""

band4 = get_sliced_band_from_L2(dataDirectory, 4, Landsat9_mtt_dict)
band3 = get_sliced_band_from_L2(dataDirectory, 3, Landsat9_mtt_dict)
band2 = get_sliced_band_from_L2(dataDirectory, 2, Landsat9_mtt_dict)

rgb_image = np.dstack((band4, band3, band2))
rgb_image.shape

import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(35, 35))

# Plot the RGB image
plt.imshow(rgb_image)
plt.title('Landsat 9 RGB Image')
plt.axis('off')  # Turn off axis labels
plt.show()

""":exclamation: Check the warning you received when you plotted this image

Plot histograms of a band:
"""

plt.figure()
plt.hist(band4.values.flatten(), bins = 100, color='gray', alpha=0.7)
plt.title("Histogram of a single band")
plt.xlabel("band values [reflectance]")
plt.ylabel("Count");

""":question: Is the distribution skewed? If so, is it skewed left or skewed right?"""

# Normalize/Scale the data to numbers between 0 and 1 with minimum set to zero and max set to 1.
def scaling_min_max(array, print_min_max_values = False):
    array_min, array_max = np.nanmin(array), np.nanmax(array)
    if print_min_max_values:
        print(array_min, array_max)
    return (array - array_min) / (array_max - array_min)

band4_scaled = scaling_min_max(band4, print_min_max_values=True)
band3_scaled = scaling_min_max(band3)
band2_scaled = scaling_min_max(band2)
rgb_image_scaled = np.dstack((band4_scaled, band3_scaled, band2_scaled))

plt.figure()
plt.hist(band4_scaled.values.flatten(), bins = 100, color='gray', alpha=0.7)
plt.title("Histogram of a single band [after scaling]")
plt.xlabel("band values [reflectance]")
plt.ylabel("Count");

fig, ax = plt.subplots(figsize=(35, 35))

# Plot the RGB image
plt.imshow(rgb_image_scaled)
plt.title('Landsat 9 RGB Image')
plt.axis('off')  # Turn off axis labels
plt.show()

""":exclamation: There is almost no change!"""

# Normalize/Scale the data to numbers between 0 and 1 with 2nd percentile and 98th percentile set
# to zero and max set to 1, respectively.
def scaling_percentile_based(array, low_percentile = 2, high_percentile = 98, print_scale_values = False):

    array_low, array_high =  np.nanpercentile(array, low_percentile), np.nanpercentile(array, high_percentile)

    if print_scale_values:
        print(array_low, array_high)

    scaled_array = (array - array_low) / (array_high - array_low)

    # All values above the "high" are set to 1
    mask = scaled_array >= 1.0
    scaled_array = scaled_array.where(~mask, 1.0)

    # All values below the "low" are set to 0
    mask = scaled_array <= 0
    scaled_array = scaled_array.where(~mask, 0)

    return scaled_array

band4_scaled = scaling_percentile_based(band4)
band3_scaled = scaling_percentile_based(band3)
band2_scaled = scaling_percentile_based(band2)
rgb_image_scaled = np.dstack((band4_scaled, band3_scaled, band2_scaled))

np.nanmax(band4_scaled)

plt.figure()
plt.hist(band3_scaled.values.flatten(), bins = 100, color='gray', alpha=0.7)
plt.title("Histogram of a single band [after scaling]")
plt.xlabel("band values [reflectance]")
plt.ylabel("Count");

fig, ax = plt.subplots(figsize=(35, 35))

# Plot the RGB image
plt.imshow(rgb_image_scaled)
plt.title('Landsat 9 RGB Image')
plt.axis('off')  # Turn off axis labels
plt.show()

"""#### Combination 356"""

band3 = get_sliced_band_from_L2(dataDirectory, 3, Landsat9_mtt_dict)
band5 = get_sliced_band_from_L2(dataDirectory, 5, Landsat9_mtt_dict)
band6 = get_sliced_band_from_L2(dataDirectory, 6, Landsat9_mtt_dict)

band3_scaled = scaling_percentile_based(band3)
band5_scaled = scaling_percentile_based(band5)
band6_scaled = scaling_percentile_based(band6)
rgb_image_scaled_356 = np.dstack((band3_scaled, band5_scaled, band6_scaled))

fig, ax = plt.subplots(figsize=(35, 35))

# Plot the RGB image
plt.imshow(rgb_image_scaled_356)
plt.title('Landsat 9 RGB Image')
plt.axis('off')  # Turn off axis labels
plt.show()

"""#### Combination 653"""

rgb_image_scaled_653 = np.dstack((band6_scaled, band5_scaled, band3_scaled))

fig, ax = plt.subplots(figsize=(35, 35))

# Plot the RGB image
plt.imshow(rgb_image_scaled_653)
plt.title('Landsat 9 RGB Image')
plt.axis('off')  # Turn off axis labels
plt.show()

"""#### Combination 562"""

band5 = get_sliced_band_from_L2(dataDirectory, 5, Landsat9_mtt_dict)
band6 = get_sliced_band_from_L2(dataDirectory, 6, Landsat9_mtt_dict)
band2 = get_sliced_band_from_L2(dataDirectory, 2, Landsat9_mtt_dict)


band5_scaled = scaling_percentile_based(band5)
band6_scaled = scaling_percentile_based(band6)
band2_scaled = scaling_percentile_based(band2)

rgb_image_scaled_562 = np.dstack((band5_scaled, band6_scaled, band2_scaled))

fig, ax = plt.subplots(figsize=(35, 35))

# Plot the RGB image
plt.imshow(rgb_image_scaled_562)
plt.title('Landsat 9 RGB Image')
plt.axis('off')  # Turn off axis labels
plt.show()

"""#### Combination 567"""

band5 = get_sliced_band_from_L2(dataDirectory, 5, Landsat9_mtt_dict)
band6 = get_sliced_band_from_L2(dataDirectory, 6, Landsat9_mtt_dict)
band7 = get_sliced_band_from_L2(dataDirectory, 7, Landsat9_mtt_dict)


band5_scaled = scaling_percentile_based(band5)
band6_scaled = scaling_percentile_based(band6)
band7_scaled = scaling_percentile_based(band7)

rgb_image_scaled_567 = np.dstack((band5_scaled, band6_scaled, band7_scaled))

fig, ax = plt.subplots(figsize=(35, 35))

# Plot the RGB image
plt.imshow(rgb_image_scaled_567)
plt.title('Landsat 9 RGB Image')
plt.axis('off')  # Turn off axis labels
plt.show()

"""## NDVI"""

band5 = get_sliced_band_from_L2(dataDirectory, 5, Landsat9_mtt_dict)
band4 = get_sliced_band_from_L2(dataDirectory, 6, Landsat9_mtt_dict)

ndvi_slice = (band5 - band4) / (band5 + band4)

fig, ax = plt.subplots(figsize=(30, 15))

# # Plot the RGB image
# plt.imshow(ndvi_slice,cmap = 'gray')
# plt.title('Landsat 9 RGB Image')
# plt.axis('off')  # Turn off axis labels
# plt.show()

cmap = 'RdYlGn'  # Red-Yellow-Green is often used for NDVI

# Plot the NDVI image
im = ax.imshow(ndvi_slice, cmap=cmap, vmin=-1, vmax=1)  # NDVI typically ranges from -1 to 1
ax.set_title('Landsat 9 NDVI', fontsize=24)
ax.axis('off')  # Turn off axis labels

# Add colorbar
cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
cbar.set_label('NDVI Value', fontsize=20)
cbar.ax.tick_params(labelsize=16)

plt.show()